name: release

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      service:
        required: true
        type: string
    secrets:
      SSH_USER:
        required: true
      SSH_KEY:
        required: true
      SSH_HOST:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: pull new docker image
        run: ssh cloud 'cd ${{ inputs.path }} &&
          docker-compose pull ${{ inputs.service }} &&
          docker-compose up --no-deps -d --force-recreate ${{ inputs.service }}'

      - name: remove all dangling doker images
        run: ssh cloud 'docker image prune -af'
